services:
  git-repo:
    container_name: git-updater-git-repo
    image: zoeyvid/git-updater:latest
    restart: always
    network_mode: bridge
    volumes:
      - "/path/to/git-repo:/src"
    environment:
      - "TZ=Europe/Berlin"
    user: 1000:1000
